package service

import (
	"context"
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"mime"
	"mime/multipart"
	"net/url"
	"path"
	"strings"
	"time"

	werrors "github.com/Tencent/WeKnora/internal/errors"
	"github.com/Tencent/WeKnora/internal/infrastructure/chunker"
	"github.com/Tencent/WeKnora/internal/infrastructure/docparser"
	"github.com/Tencent/WeKnora/internal/logger"
	"github.com/Tencent/WeKnora/internal/tracing/langfuse"
	"github.com/Tencent/WeKnora/internal/types"
	"github.com/Tencent/WeKnora/internal/types/interfaces"
	secutils "github.com/Tencent/WeKnora/internal/utils"
	"github.com/google/uuid"
	"github.com/hibiken/asynq"
)

// ValidateStoredKnowledgeUpload authorizes a direct upload before bytes are
// sent to an S3-compatible store.
func (s *knowledgeService) ValidateStoredKnowledgeUpload(
	ctx context.Context,
	kbID string,
	fileName string,
	size int64,
	contentType string,
) error {
	if s == nil || s.kbService == nil {
		return fmt.Errorf("knowledge service is not configured")
	}
	kb, err := s.kbService.GetKnowledgeBaseByID(ctx, kbID)
	if err != nil {
		return err
	}
	if kb == nil {
		return werrors.NewNotFoundError("knowledge base not found")
	}
	if kb.Type == types.KnowledgeBaseTypeFAQ {
		return werrors.NewBadRequestError("FAQ 知识库不支持文件上传，请使用 FAQ 导入功能")
	}
	if err := s.checkStorageEngineConfigured(ctx, kb); err != nil {
		return err
	}
	if strings.TrimSpace(fileName) == "" || !isValidFileType(fileName) || !isVideoFileName(fileName, contentType) {
		return ErrInvalidFileType
	}
	if size <= 0 || size > secutils.GetMaxVideoFileSizeBytes() {
		if size > secutils.GetMaxVideoFileSizeBytes() {
			return werrors.NewBadRequestError(VideoTooLargePublicMessage)
		}
		return werrors.NewBadRequestError("视频不能为空")
	}
	if err := s.checkCreateKnowledgeEntitlement(ctx, kbID, getFileType(fileName), size); err != nil {
		return err
	}
	tenantInfo, ok := types.TenantInfoFromContext(ctx)
	if !ok || tenantInfo == nil {
		return werrors.NewUnauthorizedError("Unauthorized")
	}
	storageQuota := effectiveStorageQuota(tenantInfo, time.Now().UTC())
	storageUsed := tenantInfo.StorageUsed
	if storageUsed < 0 {
		storageUsed = 0
	}
	if storageQuota > 0 && (storageUsed >= storageQuota || size > storageQuota-storageUsed) {
		return types.NewStorageQuotaExceededError()
	}
	return nil
}

// CreateKnowledgeFromStoredObject adopts an object that has already been
// uploaded directly to an S3-compatible store. No bytes are copied through
// the application: the verified provider URI is persisted as FilePath and
// the existing knowledge persistence/Asynq enqueue path is reused below.
func (s *knowledgeService) CreateKnowledgeFromStoredObject(
	ctx context.Context,
	uploadID string,
	kbID string,
	fileName string,
	size int64,
	contentType string,
	filePath string,
	etag string,
	deleteObject interfaces.StoredObjectDeleter,
	metadata map[string]string,
	enableMultimodel *bool,
	customFileName string,
	tagIDs []string,
	channel string,
	processOverrides *types.KnowledgeProcessOverrides,
) (*types.Knowledge, error) {
	if size <= 0 || strings.TrimSpace(filePath) == "" {
		return nil, fmt.Errorf("stored object path and size are required")
	}
	// The direct-upload intent ID is generated by the server and covered by
	// the HMAC token. Reusing it as the Knowledge primary key gives Complete a
	// database-enforced idempotency boundary: concurrent requests can race on
	// the insert, but only one can create the row.
	knowledgeID := strings.TrimSpace(uploadID)
	if knowledgeID == "" {
		// Keep this optional capability usable by internal callers that predate
		// direct-upload intents. The HTTP handler always supplies the signed ID.
		knowledgeID = uuid.NewString()
	}
	tenantIDValue, _ := ctx.Value(types.TenantIDContextKey).(uint64)
	// The object is still an orphan until the row is committed. Once the
	// database row exists, it owns the object even if tag/task bookkeeping
	// needs repair; the deferred cleanup must never remove an adopted source.
	rollback := true
	defer func() {
		if rollback && deleteObject != nil {
			// A competing Complete may have committed the deterministic row just
			// after this request lost its insert race (or while the database
			// returned an ambiguous error). Never delete an object already owned by
			// the exact tenant/KB/Knowledge row. If the lookup itself is
			// unavailable, preserve the object: ownership is uncertain and a later
			// retry can reconcile it, whereas deleting it would be irreversible.
			if s != nil && s.repo != nil && tenantIDValue != 0 {
				existing, lookupErr := s.repo.GetKnowledgeByID(ctx, tenantIDValue, knowledgeID)
				if lookupErr == nil && directKnowledgeOwnsObject(existing, tenantIDValue, kbID, filePath, size) {
					logger.Infof(ctx, "Preserving direct object already adopted by knowledge %s", knowledgeID)
					return
				}
				if lookupErr != nil {
					logger.Warnf(
						ctx,
						"Could not determine direct object ownership for %s; preserving object: %v",
						knowledgeID,
						lookupErr,
					)
					return
				}
			}
			if deleteErr := deleteObject(ctx); deleteErr != nil {
				logger.Errorf(ctx, "Failed to delete unadopted direct object %s: %v", filePath, deleteErr)
			}
		}
	}()
	if s == nil || s.kbService == nil {
		return nil, fmt.Errorf("knowledge service is not configured")
	}
	kb, err := s.kbService.GetKnowledgeBaseByID(ctx, kbID)
	if err != nil {
		return nil, err
	}
	if kb == nil {
		return nil, werrors.NewNotFoundError("knowledge base not found")
	}
	if kb.Type == types.KnowledgeBaseTypeFAQ {
		return nil, werrors.NewBadRequestError("FAQ 知识库不支持文件上传，请使用 FAQ 导入功能")
	}
	if err := s.checkStorageEngineConfigured(ctx, kb); err != nil {
		return nil, err
	}
	fileName = strings.TrimSpace(fileName)
	if fileName == "" || !isValidFileType(fileName) {
		return nil, ErrInvalidFileType
	}
	if size > secutils.GetMaxFileSize() && !isVideoFileName(fileName, contentType) {
		return nil, werrors.NewBadRequestError(fmt.Sprintf("文件大小不能超过%dMB", secutils.GetMaxFileSizeMB()))
	}
	if isVideoFileName(fileName, contentType) && size > secutils.GetMaxVideoFileSizeBytes() {
		return nil, werrors.NewBadRequestError(VideoTooLargePublicMessage)
	}
	tenantIDValue, ok := ctx.Value(types.TenantIDContextKey).(uint64)
	if !ok || tenantIDValue == 0 {
		return nil, werrors.NewUnauthorizedError("Unauthorized")
	}
	hash := strings.Trim(strings.TrimSpace(etag), `"`)
	if hash == "" {
		hash = fmt.Sprintf("direct-%x", sha256.Sum256([]byte(filePath)))
	}
	exists, existingKnowledge, err := s.repo.CheckKnowledgeExists(ctx, tenantIDValue, kbID, &types.KnowledgeCheckParams{
		Type: "file", FileName: fileName, FileType: getFileType(fileName), FileSize: size, FileHash: hash,
	})
	if err != nil {
		return nil, err
	}
	var knowledge *types.Knowledge
	var storageQuota int64
	if exists {
		if existingKnowledge == nil {
			return nil, fmt.Errorf("knowledge repository returned duplicate without a row")
		}
		// A duplicate hash from a different intent is a normal content
		// deduplication result: retain the existing row and clean only this
		// request's object. The exact intent/path is different: continue through
		// the idempotent tag and deterministic enqueue path so a replay can
		// repair work that failed after the row was committed.
		if existingKnowledge.ID != knowledgeID || existingKnowledge.FilePath != filePath {
			if existingKnowledge.FilePath == filePath {
				rollback = false
			}
			if err := s.repo.UpdateKnowledgeColumn(ctx, existingKnowledge.ID, "created_at", time.Now()); err != nil {
				return nil, err
			}
			return existingKnowledge, nil
		}
		// Mark an exact-path replay as already adopted before touching any
		// mutable metadata. Even if refreshing created_at fails, this object is
		// owned by the existing row and must never be deleted by rollback.
		rollback = false
		if err := s.repo.UpdateKnowledgeColumn(ctx, existingKnowledge.ID, "created_at", time.Now()); err != nil {
			return nil, err
		}
		knowledge = existingKnowledge
	}
	if knowledge == nil {
		if err := s.checkCreateKnowledgeEntitlement(ctx, kbID, getFileType(fileName), size); err != nil {
			return nil, err
		}
		tenantInfo, _ := ctx.Value(types.TenantInfoContextKey).(*types.Tenant)
		if tenantInfo == nil {
			return nil, werrors.NewUnauthorizedError("Unauthorized")
		}
		storageQuota = effectiveStorageQuota(tenantInfo, time.Now().UTC())
		storageUsed := tenantInfo.StorageUsed
		if storageUsed < 0 {
			storageUsed = 0
		}
		if storageQuota > 0 && (storageUsed >= storageQuota || size > storageQuota-storageUsed) {
			return nil, types.NewStorageQuotaExceededError()
		}
		folderPath, displayName := types.SplitKnowledgeRelativePath(fileName)
		if customFileName != "" {
			folderPath, displayName = types.SplitKnowledgeRelativePath(customFileName)
			if displayName == "" {
				displayName = fileName
			}
		}
		safeFilename, valid := secutils.ValidateInput(displayName)
		if !valid {
			return nil, werrors.NewValidationError("文件名包含非法字符")
		}
		if folderPath != "" {
			safeFolderPath, folderValid := secutils.ValidateInput(folderPath)
			if !folderValid {
				return nil, werrors.NewValidationError("文件夹路径包含非法字符")
			}
			folderPath = types.NormalizeKnowledgeFolderPath(safeFolderPath)
		}
		var metadataJSON types.JSON
		if metadata != nil {
			metadataBytes, marshalErr := json.Marshal(metadata)
			if marshalErr != nil {
				return nil, marshalErr
			}
			metadataJSON = types.JSON(metadataBytes)
		}
		knowledge = &types.Knowledge{
			ID:               knowledgeID,
			TenantID:         tenantIDValue,
			KnowledgeBaseID:  kbID,
			Type:             "file",
			Channel:          defaultChannel(channel),
			Title:            safeFilename,
			FileName:         safeFilename,
			FolderPath:       folderPath,
			FileType:         getFileType(safeFilename),
			FileSize:         size,
			FileHash:         hash,
			FilePath:         filePath,
			ParseStatus:      "pending",
			EnableStatus:     "disabled",
			CreatedAt:        time.Now(),
			UpdatedAt:        time.Now(),
			EmbeddingModelID: kb.EmbeddingModelID, Metadata: metadataJSON,
		}
		if processOverrides != nil {
			if err := knowledge.SetProcessOverrides(processOverrides); err != nil {
				return nil, err
			}
		}
	}
	// Replays use the persisted row's metadata and source fields, but resolve
	// the effective process configuration again so a prior queue outage can be
	// repaired by the same Complete request.
	eff, err := resolveFileImportProcessConfig(ctx, kb, knowledge.FileType, processOverrides, enableMultimodel)
	if err != nil {
		return nil, err
	}
	if err := s.persistKnowledgeAndEnqueue(
		ctx,
		kb,
		knowledge,
		storageQuota,
		tagIDs,
		eff,
		true,
		func() { rollback = false },
	); err != nil {
		return nil, err
	}
	return knowledge, nil
}

// directKnowledgeOwnsObject reports whether an existing row is the exact
// deterministic owner for a direct-upload object. The ID alone is not enough:
// a malformed or stale caller must never turn a different row into permission
// to retain/delete an object from another upload intent.
func directKnowledgeOwnsObject(
	knowledge *types.Knowledge,
	tenantID uint64,
	kbID string,
	filePath string,
	size int64,
) bool {
	if knowledge == nil {
		return false
	}
	return knowledge.TenantID == tenantID &&
		knowledge.KnowledgeBaseID == kbID &&
		knowledge.Type == "file" &&
		knowledge.FilePath == filePath &&
		knowledge.FileSize == size
}

func directKnowledgeProcessTaskID(knowledgeID string) string {
	return "knowledge-process-" + strings.TrimSpace(knowledgeID)
}

// isVideoFileName is deliberately strict for direct uploads: a video MIME
// type is accepted only when the filename extension resolves to the same
// media type. This prevents a caller from labelling a PDF as video to obtain
// the larger video byte limit.
func isVideoFileName(fileName, contentType string) bool {
	mediaType, _, err := mime.ParseMediaType(strings.TrimSpace(contentType))
	if err != nil || !strings.HasPrefix(strings.ToLower(mediaType), "video/") {
		return false
	}
	switch strings.ToLower(path.Ext(strings.TrimSpace(fileName))) {
	case ".mp4":
		return strings.EqualFold(mediaType, "video/mp4")
	case ".mpeg":
		return strings.EqualFold(mediaType, "video/mpeg")
	case ".mov":
		return strings.EqualFold(mediaType, "video/quicktime") || strings.EqualFold(mediaType, "video/mov")
	case ".webm":
		return strings.EqualFold(mediaType, "video/webm")
	default:
		return false
	}
}

// CreateKnowledgeFromFile creates a knowledge entry from an uploaded file
func (s *knowledgeService) CreateKnowledgeFromFile(ctx context.Context,
	kbID string, file *multipart.FileHeader, metadata map[string]string, enableMultimodel *bool, customFileName string, tagIDs []string, channel string,
	processOverrides *types.KnowledgeProcessOverrides,
) (*types.Knowledge, error) {
	logger.Info(ctx, "Start creating knowledge from file")

	// Use custom filename if provided, otherwise use original filename. Folder
	// uploads pass a path-qualified name ("docs/spec/design.md"): the directory
	// part becomes the knowledge's folder_path and only the base name is kept as
	// the display / storage file name.
	fileName := file.Filename
	folderPath := ""
	if customFileName != "" {
		folderPath, fileName = types.SplitKnowledgeRelativePath(customFileName)
		if fileName == "" {
			fileName = file.Filename
		}
		logger.Infof(ctx, "Using custom filename: %s (original: %s, folder: %s)",
			fileName, file.Filename, folderPath)
	}

	logger.Infof(ctx, "Knowledge base ID: %s, file: %s", kbID, fileName)

	// Get knowledge base configuration
	logger.Info(ctx, "Getting knowledge base configuration")
	kb, err := s.kbService.GetKnowledgeBaseByID(ctx, kbID)
	if err != nil {
		logger.Errorf(ctx, "Failed to get knowledge base: %v", err)
		return nil, err
	}

	// FAQ knowledge bases should not accept file uploads — use the FAQ import API instead
	if kb.Type == types.KnowledgeBaseTypeFAQ {
		return nil, werrors.NewBadRequestError("FAQ 知识库不支持文件上传，请使用 FAQ 导入功能")
	}

	if err := s.checkStorageEngineConfigured(ctx, kb); err != nil {
		return nil, err
	}

	// Early reject before the whole-file hash below. resolveFileImportProcessConfig
	// gates the same extension set, but this path must keep returning
	// ErrInvalidFileType rather than the shared gate's localized message.
	logger.Infof(ctx, "Checking file type: %s", fileName)
	if !isValidFileType(fileName) {
		logger.Error(ctx, "Invalid file type")
		return nil, ErrInvalidFileType
	}
	if IsVideoType(getFileType(fileName)) && file.Size > secutils.GetMaxVideoFileSizeBytes() {
		logger.Warnf(
			ctx,
			"Rejected oversized video before hashing: size=%d max=%d",
			file.Size,
			secutils.GetMaxVideoFileSizeBytes(),
		)
		return nil, werrors.NewBadRequestError(VideoTooLargePublicMessage)
	}

	// Calculate file hash for deduplication
	logger.Info(ctx, "Calculating file hash")
	hash, err := calculateFileHash(file)
	if err != nil {
		logger.Errorf(ctx, "Failed to calculate file hash: %v", err)
		return nil, err
	}

	// Check if file already exists
	tenantID := ctx.Value(types.TenantIDContextKey).(uint64)
	logger.Infof(ctx, "Checking if file exists, tenant ID: %d", tenantID)
	exists, existingKnowledge, err := s.repo.CheckKnowledgeExists(ctx, tenantID, kbID, &types.KnowledgeCheckParams{
		Type:     "file",
		FileName: fileName,
		FileType: getFileType(fileName),
		FileSize: file.Size,
		FileHash: hash,
	})
	if err != nil {
		logger.Errorf(ctx, "Failed to check knowledge existence: %v", err)
		return nil, err
	}
	if exists {
		logger.Infof(ctx, "File already exists: %s", fileName)
		// Update creation time for existing knowledge
		if err := s.repo.UpdateKnowledgeColumn(ctx, existingKnowledge.ID, "created_at", time.Now()); err != nil {
			logger.Errorf(ctx, "Failed to update existing knowledge: %v", err)
			return nil, err
		}
		return existingKnowledge, types.NewDuplicateFileError(existingKnowledge)
	}
	if err := s.checkCreateKnowledgeEntitlement(ctx, kbID, getFileType(fileName), file.Size); err != nil {
		return nil, err
	}

	// Check storage quota
	tenantInfo := ctx.Value(types.TenantInfoContextKey).(*types.Tenant)
	storageQuota := effectiveStorageQuota(tenantInfo, time.Now().UTC())
	storageUsed := tenantInfo.StorageUsed
	if storageUsed < 0 {
		storageUsed = 0
	}
	fileBytes := file.Size
	if fileBytes < 0 {
		fileBytes = 0
	}
	if storageQuota > 0 && (storageUsed >= storageQuota || fileBytes > storageQuota-storageUsed) {
		logger.Error(ctx, "Storage quota exceeded")
		return nil, types.NewStorageQuotaExceededError()
	}

	// Convert metadata to JSON format if provided
	var metadataJSON types.JSON
	if metadata != nil {
		metadataBytes, err := json.Marshal(metadata)
		if err != nil {
			logger.Errorf(ctx, "Failed to marshal metadata: %v", err)
			return nil, err
		}
		metadataJSON = types.JSON(metadataBytes)
	}

	// 验证文件名安全性
	safeFilename, isValid := secutils.ValidateInput(fileName)
	if !isValid {
		logger.Errorf(ctx, "Invalid filename: %s", fileName)
		return nil, werrors.NewValidationError("文件名包含非法字符")
	}

	// The folder path is rendered as sidebar tree labels, so it goes through the
	// same input validation as the file name before it is stored.
	if folderPath != "" {
		safeFolderPath, folderValid := secutils.ValidateInput(folderPath)
		if !folderValid {
			logger.Errorf(ctx, "Invalid folder path: %s", folderPath)
			return nil, werrors.NewValidationError("文件夹路径包含非法字符")
		}
		folderPath = types.NormalizeKnowledgeFolderPath(safeFolderPath)
	}

	eff, err := resolveFileImportProcessConfig(ctx, kb, getFileType(safeFilename), processOverrides, enableMultimodel)
	if err != nil {
		return nil, err
	}

	// Prepare knowledge record
	logger.Info(ctx, "Preparing knowledge record")
	knowledge := &types.Knowledge{
		ID:               uuid.New().String(),
		TenantID:         tenantID,
		KnowledgeBaseID:  kbID,
		Type:             "file",
		Channel:          defaultChannel(channel),
		Title:            safeFilename,
		FileName:         safeFilename,
		FolderPath:       folderPath,
		FileType:         getFileType(safeFilename),
		FileSize:         file.Size,
		FileHash:         hash,
		ParseStatus:      "pending",
		EnableStatus:     "disabled",
		CreatedAt:        time.Now(),
		UpdatedAt:        time.Now(),
		EmbeddingModelID: kb.EmbeddingModelID,
		Metadata:         metadataJSON,
	}

	if processOverrides != nil {
		if err := knowledge.SetProcessOverrides(processOverrides); err != nil {
			logger.Errorf(ctx, "Failed to set process overrides: %v", err)
			return nil, err
		}
	}

	// Save the file to storage (use KB-level storage engine if configured)
	logger.Infof(ctx, "Saving file, knowledge ID: %s", knowledge.ID)
	fileSvc := s.resolveFileService(ctx, kb)
	filePath, err := fileSvc.SaveFile(ctx, file, knowledge.TenantID, knowledge.ID)
	if err != nil {
		logger.Errorf(ctx, "Failed to save file, knowledge ID: %s, error: %v", knowledge.ID, err)
		return nil, err
	}
	knowledge.FilePath = filePath

	persisted := false
	if err := s.persistKnowledgeAndEnqueue(
		ctx,
		kb,
		knowledge,
		storageQuota,
		tagIDs,
		eff,
		false,
		func() { persisted = true },
	); err != nil {
		if !persisted {
			if deleteErr := fileSvc.DeleteFile(ctx, filePath); deleteErr != nil {
				logger.Errorf(
					ctx,
					"Failed to delete saved file after knowledge creation failed, path: %s, error: %v",
					filePath,
					deleteErr,
				)
			}
		}
		return nil, err
	}

	logger.Infof(ctx, "Knowledge from file created successfully, ID: %s", knowledge.ID)
	return knowledge, nil
}

// persistKnowledgeAndEnqueue is the shared ownership hand-off for file
// imports. Callers store the file (or adopt an already stored provider URI),
// then invoke this helper; onPersisted fires immediately after the database
// row owns that URI so a caller can stop its pre-adoption rollback.
func (s *knowledgeService) persistKnowledgeAndEnqueue(
	ctx context.Context,
	kb *types.KnowledgeBase,
	knowledge *types.Knowledge,
	storageQuota int64,
	tagIDs []string,
	eff types.EffectiveProcessConfig,
	strictEnqueue bool,
	onPersisted func(),
) error {
	logger.Info(ctx, "Saving knowledge record to database")
	if err := s.repo.CreateKnowledgeWithStorage(ctx, knowledge, storageQuota); err != nil {
		// A direct Complete retry can lose the insert race after another request
		// has already committed the same deterministic Knowledge ID. Recover only
		// when the persisted row points at the exact object and scope; all other
		// errors retain their original behavior and keep the rollback armed.
		if strictEnqueue {
			existing, lookupErr := s.repo.GetKnowledgeByID(ctx, knowledge.TenantID, knowledge.ID)
			if lookupErr == nil && directKnowledgeOwnsObject(
				existing,
				knowledge.TenantID,
				knowledge.KnowledgeBaseID,
				knowledge.FilePath,
				knowledge.FileSize,
			) {
				*knowledge = *existing
				logger.Infof(
					ctx,
					"Direct knowledge insert already committed, continuing idempotent completion: ID=%s",
					knowledge.ID,
				)
			} else {
				logger.Errorf(ctx, "Failed to create knowledge record, ID: %s, error: %v", knowledge.ID, err)
				return err
			}
		} else {
			logger.Errorf(ctx, "Failed to create knowledge record, ID: %s, error: %v", knowledge.ID, err)
			return err
		}
	}
	// A committed row owns its source immediately. Direct Complete retries use
	// the same callback after an exact-row recovery above, so both winner and
	// loser requests leave object cleanup disarmed before tags or queue work.
	if onPersisted != nil {
		onPersisted()
	}
	if err := s.setAndAttachKnowledgeTags(
		ctx,
		knowledge.TenantID,
		knowledge.KnowledgeBaseID,
		knowledge,
		tagIDs,
	); err != nil {
		logger.Errorf(ctx, "Failed to set knowledge tags, knowledge ID: %s, error: %v", knowledge.ID, err)
		return err
	}

	logger.Info(ctx, "Enqueuing document processing task to Asynq")
	enableQuestionGeneration := eff.QuestionGenerationConfig.Enabled
	questionCount := eff.QuestionGenerationConfig.QuestionCount
	if questionCount <= 0 {
		questionCount = 3
	}
	taskPayload := types.DocumentProcessPayload{
		TenantID:                 knowledge.TenantID,
		KnowledgeID:              knowledge.ID,
		KnowledgeBaseID:          knowledge.KnowledgeBaseID,
		FilePath:                 knowledge.FilePath,
		FileName:                 knowledge.FileName,
		FileType:                 knowledge.FileType,
		EnableMultimodel:         eff.EnableMultimodel,
		EnableQuestionGeneration: enableQuestionGeneration,
		QuestionCount:            questionCount,
		Language:                 types.LanguageFromContextOrDefault(ctx),
	}
	langfuse.InjectTracing(ctx, &taskPayload)
	payloadBytes, err := json.Marshal(taskPayload)
	if err != nil {
		logger.Errorf(ctx, "Failed to marshal document process task payload: %v", err)
		s.markKnowledgeEnqueueFailed(ctx, knowledge)
		recordKBActivity(ctx, s.audit, knowledge.TenantID, knowledge.KnowledgeBaseID, types.AuditActionKnowledgeCreated,
			"knowledge", knowledge.ID, types.AuditOutcomeFailed, map[string]any{
				"title": knowledge.Title, "source_type": "file", "file_type": knowledge.FileType,
				"processing_status": "failed", "failure_stage": "enqueue",
			})
		if strictEnqueue {
			// The row already owns the source. Keep it available for repair rather
			// than deleting an object another Complete request may be adopting.
			return fmt.Errorf("marshal document process task payload: %w", err)
		}
		return nil
	}
	taskOptions := documentProcessTaskOptions(s.config, asynq.MaxRetry(3))
	processTaskID := ""
	if strictEnqueue {
		// The same direct-upload intent must map to one parser task as well as
		// one Knowledge row. Asynq's conflict sentinel is an acknowledgement
		// that another Complete request already accepted this task.
		processTaskID = directKnowledgeProcessTaskID(knowledge.ID)
		taskOptions = documentProcessTaskOptions(s.config, asynq.TaskID(processTaskID), asynq.MaxRetry(3))
	}
	task := asynq.NewTask(types.TypeDocumentProcess, payloadBytes, taskOptions...)
	var info *asynq.TaskInfo
	var enqueueErr error
	const maxDirectEnqueueAttempts = 3
	attempts := 1
	if strictEnqueue {
		attempts = maxDirectEnqueueAttempts
	}
	for attempt := 1; attempt <= attempts; attempt++ {
		if strictEnqueue {
			// SyncTaskExecutor (Lite mode) receives options at Enqueue time;
			// passing them here keeps the deterministic task ID effective for both
			// the in-process and Redis-backed enqueuers. Redis merges these with the
			// same options already embedded in the task, with the latter values
			// remaining identical.
			info, enqueueErr = s.task.Enqueue(task, taskOptions...)
		} else {
			info, enqueueErr = s.task.Enqueue(task)
		}
		if enqueueErr == nil {
			break
		}
		if strictEnqueue && (errors.Is(enqueueErr, asynq.ErrTaskIDConflict) ||
			errors.Is(enqueueErr, asynq.ErrDuplicateTask)) {
			// A conflict means the task was accepted by a competing request;
			// treat it as success and use the deterministic ID for the audit log.
			info = &asynq.TaskInfo{ID: processTaskID, Queue: types.QueueDefault}
			enqueueErr = nil
			break
		}
		if attempt < attempts {
			logger.Warnf(
				ctx,
				"Retrying document process enqueue for knowledge %s (attempt %d/%d): %v",
				knowledge.ID,
				attempt+1,
				attempts,
				enqueueErr,
			)
		}
	}
	err = enqueueErr
	if err != nil {
		logger.Errorf(ctx, "Failed to enqueue document process task: %v", err)
		s.markKnowledgeEnqueueFailed(ctx, knowledge)
		recordKBActivity(ctx, s.audit, knowledge.TenantID, knowledge.KnowledgeBaseID, types.AuditActionKnowledgeCreated,
			"knowledge", knowledge.ID, types.AuditOutcomeFailed, map[string]any{
				"title": knowledge.Title, "source_type": "file", "file_type": knowledge.FileType,
				"processing_status": "failed", "failure_stage": "enqueue",
			})
		if strictEnqueue {
			// The row already owns the source. Keep both available for a later
			// repair/retry instead of deleting an object another Complete request
			// may already have adopted.
			return fmt.Errorf("enqueue document process task: %w", err)
		}
		return nil
	}
	recordKBActivity(ctx, s.audit, knowledge.TenantID, knowledge.KnowledgeBaseID, types.AuditActionKnowledgeCreated,
		"knowledge", knowledge.ID, types.AuditOutcomeAccepted, map[string]any{
			"title": knowledge.Title, "source_type": "file", "file_type": knowledge.FileType,
			"processing_status": "pending", "task_id": info.ID, "trigger": kbActivityTrigger(ctx),
		})
	logger.Infof(
		ctx,
		"Enqueued document process task: id=%s queue=%s knowledge_id=%s",
		info.ID,
		info.Queue,
		knowledge.ID,
	)
	enqueueDataTableSummaryIfNeeded(
		ctx,
		s.task,
		knowledge.TenantID,
		knowledge.ID,
		knowledge.FileName,
		knowledge.FileType,
		kb.SummaryModelID,
		kb.EmbeddingModelID,
	)
	return nil
}

// CreateKnowledgeFromURL creates a knowledge entry from a URL source
// tagID is optional - when provided, the knowledge will be assigned to the specified tag/category.
// isFileURL reports whether the given URL should be treated as a direct file download.
// Priority: URL path has a known file extension first, then fall back to user-provided fileName/fileType hints.
func isFileURL(rawURL, fileName, fileType string) bool {
	u, err := url.Parse(rawURL)
	if err == nil {
		ext := strings.ToLower(strings.TrimPrefix(path.Ext(u.Path), "."))
		if ext != "" && isSupportedImportExtension(ext) {
			return true
		}
	}
	// Fall back to user-provided hints
	return fileName != "" || fileType != ""
}

func (s *knowledgeService) CreateKnowledgeFromURL(ctx context.Context,
	kbID string, rawURL string, fileName string, fileType string, enableMultimodel *bool, title string, tagIDs []string, channel string,
	processOverrides *types.KnowledgeProcessOverrides,
) (*types.Knowledge, error) {
	// Accept either a naked URL or a copied share message. Classification is
	// deliberately pure and happens before file detection/SSRF checks so a
	// known social host cannot be sent to the generic WebParser path. The
	// parser's errors contain no input, which keeps pasted share text out of
	// logs and public error payloads.
	socialRoute, cleanedURL, parseErr := ParseSocialShareInput(rawURL)
	if parseErr != nil {
		logger.Warnf(ctx, "Rejected URL share input: %v", parseErr)
		return nil, werrors.NewBadRequestError(parseErr.Error())
	}
	logger.Info(ctx, "Start creating knowledge from URL")
	url := cleanedURL
	if socialRoute != nil {
		logger.Infof(ctx, "Recognized social URL: platform=%s object_id_present=%t", socialRoute.Platform, socialRoute.ObjectID != "")
	}
	if plan, ok := effectivePlanFromContext(ctx); isLiteProductEdition() && ok && plan == types.ConsumerPlanFree {
		return nil, werrors.NewForbiddenError("Free plan does not support URL import")
	}

	// Route to file_url logic when the URL points to a downloadable file
	// A recognized social work always follows the social document path. File
	// hints are retained for ordinary URLs only, preserving the existing direct
	// file import behavior without allowing a social page to be downloaded as a
	// generic file.
	if socialRoute == nil && isFileURL(url, fileName, fileType) {
		return s.createKnowledgeFromFileURL(
			ctx, kbID, url, fileName, fileType, enableMultimodel, title, tagIDs, channel, processOverrides,
		)
	}

	// Get knowledge base configuration
	logger.Info(ctx, "Getting knowledge base configuration")
	kb, err := s.kbService.GetKnowledgeBaseByID(ctx, kbID)
	if err != nil {
		logger.Errorf(ctx, "Failed to get knowledge base: %v", err)
		return nil, err
	}

	if err := s.checkStorageEngineConfigured(ctx, kb); err != nil {
		return nil, err
	}

	// Validate URL format and security
	logger.Info(ctx, "Validating URL")
	if !isValidURL(url) || !secutils.IsValidURL(url) {
		logger.Error(ctx, "Invalid or unsafe URL format")
		return nil, ErrInvalidURL
	}

	// Ordinary URLs are fetched by Musuw and therefore need the central SSRF
	// gate. Recognized social URLs are only sent as data to TikHub's fixed API
	// host; the exact host/path router above is their allowlist, and any media
	// URL returned by TikHub is validated separately before download.
	if socialRoute == nil {
		if err := secutils.ValidateURLForSSRF(url); err != nil {
			logger.Errorf(ctx, "URL rejected for SSRF protection: host_path=%s, err: %v", urlForLog(url), err)
			return nil, ErrInvalidURL
		}
	}

	// Check if URL already exists in the knowledge base
	tenantID := ctx.Value(types.TenantIDContextKey).(uint64)
	logger.Infof(ctx, "Checking if URL exists, tenant ID: %d", tenantID)
	fileHash := calculateStr(socialURLDedupeSource(socialRoute, url))
	exists, existingKnowledge, err := s.repo.CheckKnowledgeExists(ctx, tenantID, kbID, &types.KnowledgeCheckParams{
		Type:              "url",
		URL:               url,
		FileHash:          fileHash,
		ReuseStoredSource: socialRoute != nil,
	})
	if err != nil {
		logger.Errorf(ctx, "Failed to check knowledge existence: %v", err)
		return nil, err
	}
	if exists && socialRoute != nil && strings.TrimSpace(existingKnowledge.FilePath) != "" {
		if sourceErr := s.validateMaterializedSocialSource(ctx, kb, existingKnowledge); sourceErr != nil {
			// A stale catalog row is not a reusable object. Continue with a fresh
			// source acquisition instead of trapping every resubmission on a path
			// that can no longer be read.
			logger.Warnf(ctx, "Stored social source is not reusable, knowledge=%s: %v", existingKnowledge.ID, sourceErr)
			exists = false
		}
	}
	if exists {
		return s.handleExistingURLKnowledge(ctx, existingKnowledge, socialRoute != nil, url, processOverrides)
	}
	if err := s.checkCreateKnowledgeEntitlement(ctx, kbID, "html", 1024*1024); err != nil {
		return nil, err
	}

	// Check storage quota
	tenantInfo := ctx.Value(types.TenantInfoContextKey).(*types.Tenant)
	storageQuota := effectiveStorageQuota(tenantInfo, time.Now().UTC())
	if storageQuota > 0 && tenantInfo.StorageUsed >= storageQuota {
		logger.Error(ctx, "Storage quota exceeded")
		return nil, types.NewStorageQuotaExceededError()
	}

	// Create knowledge record
	logger.Info(ctx, "Creating knowledge record")
	knowledge := &types.Knowledge{
		ID:               uuid.New().String(),
		TenantID:         tenantID,
		KnowledgeBaseID:  kbID,
		Type:             "url",
		Channel:          defaultChannel(channel),
		Title:            title,
		Source:           url,
		FileType:         "html",
		FileHash:         fileHash,
		ParseStatus:      "pending",
		EnableStatus:     "disabled",
		CreatedAt:        time.Now(),
		UpdatedAt:        time.Now(),
		EmbeddingModelID: kb.EmbeddingModelID,
	}

	// Save knowledge record
	logger.Infof(ctx, "Saving knowledge record to database, ID: %s", knowledge.ID)
	eff, err := ApplyKnowledgeProcessOverrides(ctx, kb, knowledge, processOverrides, []string{"html"}, enableMultimodel)
	if err != nil {
		return nil, err
	}

	if socialRoute != nil {
		// The fast duplicate check above preserves the existing reparse/stale-
		// source behavior. This transactional claim is the final authority for
		// simultaneous submissions: only its winner can attach tags or enqueue a
		// paid provider task.
		claimedKnowledge, created, claimErr := s.repo.CreateURLKnowledgeIfAbsent(
			ctx,
			knowledge,
			&types.KnowledgeCheckParams{Type: "url", URL: url, FileHash: fileHash},
		)
		if claimErr != nil {
			logger.Errorf(ctx, "Failed to claim social knowledge record: %v", claimErr)
			return nil, claimErr
		}
		if !created {
			return s.handleExistingURLKnowledge(ctx, claimedKnowledge, true, url, processOverrides)
		}
		knowledge = claimedKnowledge
	} else if err := s.repo.CreateKnowledge(ctx, knowledge); err != nil {
		logger.Errorf(ctx, "Failed to create knowledge record: %v", err)
		return nil, err
	}
	// Set tag relations
	if err := s.setAndAttachKnowledgeTags(ctx, tenantID, kbID, knowledge, tagIDs); err != nil {
		logger.Errorf(ctx, "Failed to set knowledge tags, knowledge ID: %s, error: %v", knowledge.ID, err)
		return nil, err
	}

	// Enqueue URL processing task to Asynq
	logger.Info(ctx, "Enqueuing URL processing task to Asynq")
	enableMultimodelValue := eff.EnableMultimodel
	enableQuestionGeneration := eff.QuestionGenerationConfig.Enabled
	questionCount := eff.QuestionGenerationConfig.QuestionCount
	if questionCount <= 0 {
		questionCount = 3
	}

	lang := types.LanguageFromContextOrDefault(ctx)
	taskPayload := types.DocumentProcessPayload{
		TenantID:                 tenantID,
		KnowledgeID:              knowledge.ID,
		KnowledgeBaseID:          kbID,
		URL:                      url,
		EnableMultimodel:         enableMultimodelValue,
		EnableQuestionGeneration: enableQuestionGeneration,
		QuestionCount:            questionCount,
		Language:                 lang,
	}

	langfuse.InjectTracing(ctx, &taskPayload)
	payloadBytes, err := json.Marshal(taskPayload)
	if err != nil {
		logger.Errorf(ctx, "Failed to marshal URL process task payload: %v", err)
		s.markKnowledgeEnqueueFailed(ctx, knowledge)
		recordKBActivity(ctx, s.audit, tenantID, kbID, types.AuditActionKnowledgeCreated,
			"knowledge", knowledge.ID, types.AuditOutcomeFailed, map[string]any{
				"title": knowledge.Title, "source_type": "url", "file_type": knowledge.FileType,
				"processing_status": "failed", "failure_stage": "enqueue",
			})
		return knowledge, nil
	}

	taskOpts := documentProcessTaskOptions(s.config)
	var enqueueOpts []asynq.Option
	if socialRoute != nil {
		// TikHub materializes the social source as a durable file before the
		// existing document pipeline parses it. On a downstream retry the worker
		// restores that FilePath checkpoint and skips TikHub, so social videos can
		// use the normal document retry budget without downloading or billing the
		// source again. Lite mode can only read options passed to Enqueue, while
		// Redis-backed Asynq also reads the task's options; pass the same set to
		// both so the two runtimes keep identical retry behavior.
		enqueueOpts = taskOpts
	}
	task := asynq.NewTask(types.TypeDocumentProcess, payloadBytes, taskOpts...)
	info, err := s.task.Enqueue(task, enqueueOpts...)
	if err != nil {
		logger.Errorf(ctx, "Failed to enqueue URL process task: %v", err)
		s.markKnowledgeEnqueueFailed(ctx, knowledge)
		recordKBActivity(ctx, s.audit, tenantID, kbID, types.AuditActionKnowledgeCreated,
			"knowledge", knowledge.ID, types.AuditOutcomeFailed, map[string]any{
				"title": knowledge.Title, "source_type": "url", "file_type": knowledge.FileType,
				"processing_status": "failed", "failure_stage": "enqueue",
			})
		return knowledge, nil
	}
	recordKBActivity(ctx, s.audit, tenantID, kbID, types.AuditActionKnowledgeCreated,
		"knowledge", knowledge.ID, types.AuditOutcomeAccepted, map[string]any{
			"title": knowledge.Title, "source_type": "url", "file_type": knowledge.FileType,
			"processing_status": "pending", "task_id": info.ID, "trigger": kbActivityTrigger(ctx),
		})
	logger.Infof(ctx, "Enqueued URL process task: id=%s queue=%s knowledge_id=%s", info.ID, info.Queue, knowledge.ID)

	logger.Infof(ctx, "Knowledge from URL created successfully, ID: %s", knowledge.ID)
	return knowledge, nil
}

func (s *knowledgeService) handleExistingURLKnowledge(
	ctx context.Context,
	existing *types.Knowledge,
	social bool,
	rawURL string,
	processOverrides *types.KnowledgeProcessOverrides,
) (*types.Knowledge, error) {
	if existing == nil {
		return nil, errors.New("duplicate URL claim returned no knowledge")
	}
	logger.Infof(ctx, "URL already exists: host_path=%s", urlForLog(rawURL))
	existing.CreatedAt = time.Now()
	existing.UpdatedAt = time.Now()
	if err := s.repo.UpdateKnowledge(ctx, existing); err != nil {
		logger.Errorf(ctx, "Failed to update existing knowledge: %v", err)
		return nil, err
	}
	if social && existing.ParseStatus == types.ParseStatusFailed && strings.TrimSpace(existing.FilePath) != "" {
		logger.Infof(ctx, "Reusing materialized social source for knowledge %s", existing.ID)
		return s.ReparseKnowledge(ctx, existing.ID, processOverrides)
	}
	return existing, types.NewDuplicateURLError(existing)
}

// validateMaterializedSocialSource verifies that a dedupe hit is a readable,
// active object before it suppresses another provider fetch. It deliberately
// opens and closes the existing source without consuming it; the reparse worker
// later creates its own signed URL/read handle for the same object.
func (s *knowledgeService) validateMaterializedSocialSource(
	ctx context.Context,
	kb *types.KnowledgeBase,
	knowledge *types.Knowledge,
) error {
	if knowledge == nil || strings.TrimSpace(knowledge.FilePath) == "" {
		return errors.New("stored social source path is empty")
	}
	if _, ok := types.ParseResourcePath(knowledge.FilePath); ok {
		if s.resourceCatalog == nil {
			return errors.New("stored social source catalog is unavailable")
		}
		resource, err := s.resourceCatalog.Resolve(ctx, knowledge.FilePath)
		if err != nil {
			return fmt.Errorf("resolve stored social source: %w", err)
		}
		if resource == nil || resource.State != types.ResourceStateActive {
			return errors.New("stored social source is inactive")
		}
	}
	if IsVideoType(knowledge.FileType) {
		size, err := s.authoritativeVideoSourceSize(ctx, knowledge, knowledge.FilePath)
		if err != nil {
			return err
		}
		if size > secutils.GetMaxVideoFileSizeBytes() {
			return fmt.Errorf("stored social video size %d exceeds product maximum", size)
		}
	}
	fileSvc := s.resolveFileServiceForPath(ctx, kb, knowledge.FilePath)
	if fileSvc == nil {
		return errors.New("stored social source service is unavailable")
	}
	reader, err := fileSvc.GetFile(ctx, knowledge.FilePath)
	if err != nil {
		return fmt.Errorf("open stored social source: %w", err)
	}
	if reader == nil {
		return errors.New("stored social source reader is nil")
	}
	if err := reader.Close(); err != nil {
		return fmt.Errorf("close stored social source: %w", err)
	}
	return nil
}

// maxFileURLSize is the maximum allowed file size for file URL import (10MB)
const maxFileURLSize = 10 * 1024 * 1024

// extractFileNameFromURL extracts the filename from a URL path
func extractFileNameFromURL(rawURL string) string {
	u, err := url.Parse(rawURL)
	if err != nil {
		return ""
	}
	base := path.Base(u.Path)
	if base == "." || base == "/" {
		return ""
	}
	return base
}

// extractFileNameFromContentDisposition extracts filename from Content-Disposition header
func extractFileNameFromContentDisposition(header string) string {
	// e.g. attachment; filename="document.pdf" or filename*=UTF-8''document.pdf
	for _, part := range strings.Split(header, ";") {
		part = strings.TrimSpace(part)
		if strings.HasPrefix(strings.ToLower(part), "filename=") {
			name := strings.TrimPrefix(part, "filename=")
			name = strings.TrimPrefix(part[len("filename="):], "")
			name = strings.Trim(name, `"'`)
			if name != "" {
				return name
			}
		}
	}
	return ""
}

// createKnowledgeFromFileURL is the internal implementation for file URL knowledge creation.
// Called by CreateKnowledgeFromURL when the URL is detected as a direct file download.
func (s *knowledgeService) createKnowledgeFromFileURL(
	ctx context.Context,
	kbID string,
	fileURL string,
	fileName string,
	fileType string,
	enableMultimodel *bool,
	title string,
	tagIDs []string,
	channel string,
	processOverrides *types.KnowledgeProcessOverrides,
) (*types.Knowledge, error) {
	logger.Info(ctx, "Start creating knowledge from file URL")
	logger.Infof(ctx, "Knowledge base ID: %s, file URL host_path: %s", kbID, urlForLog(fileURL))

	// Get knowledge base configuration
	kb, err := s.kbService.GetKnowledgeBaseByID(ctx, kbID)
	if err != nil {
		logger.Errorf(ctx, "Failed to get knowledge base: %v", err)
		return nil, err
	}

	if kb.Type == types.KnowledgeBaseTypeFAQ {
		return nil, werrors.NewBadRequestError("FAQ 知识库不支持文件上传，请使用 FAQ 导入功能")
	}

	if err := s.checkStorageEngineConfigured(ctx, kb); err != nil {
		return nil, err
	}

	// Validate URL format and security (static check only, no HEAD request)
	if !isValidURL(fileURL) || !secutils.IsValidURL(fileURL) {
		logger.Error(ctx, "Invalid or unsafe file URL format")
		return nil, ErrInvalidURL
	}
	if err := secutils.ValidateURLForSSRF(fileURL); err != nil {
		logger.Errorf(ctx, "File URL rejected for SSRF protection: host_path=%s, err: %v", urlForLog(fileURL), err)
		return nil, ErrInvalidURL
	}

	// Resolve fileName: user-provided > extracted from URL path
	if fileName == "" {
		fileName = extractFileNameFromURL(fileURL)
	}
	if fileName != "" {
		safeFilename, ok := secutils.ValidateInput(fileName)
		if !ok {
			logger.Errorf(ctx, "Invalid filename: %s", fileName)
			return nil, werrors.NewValidationError("文件名包含非法字符")
		}
		fileName = safeFilename
	}

	// Resolve fileType: user-provided > inferred from fileName (which already
	// falls back to the URL path above). getFileType never returns empty, so an
	// undeterminable type surfaces as "unknown" and is rejected below.
	if fileType == "" {
		fileType = getFileType(fileName)
	}
	fileType = normalizeFileExtension(fileType)

	// Use title as display name if fileName is still empty
	displayName := fileName
	if displayName == "" {
		displayName = title
	}
	if displayName == "" {
		// Fallback: use last segment of URL
		displayName = extractFileNameFromURL(fileURL)
	}
	if displayName == "" {
		displayName = fileURL
	}

	// Check for duplicate (by URL hash)
	tenantID := ctx.Value(types.TenantIDContextKey).(uint64)
	fileHash := calculateStr(fileURL)
	exists, existingKnowledge, err := s.repo.CheckKnowledgeExists(ctx, tenantID, kbID, &types.KnowledgeCheckParams{
		Type:     "file_url",
		URL:      fileURL,
		FileHash: fileHash,
	})
	if err != nil {
		logger.Errorf(ctx, "Failed to check knowledge existence: %v", err)
		return nil, err
	}
	if exists {
		logger.Infof(ctx, "File URL already exists: host_path=%s", urlForLog(fileURL))
		existingKnowledge.CreatedAt = time.Now()
		existingKnowledge.UpdatedAt = time.Now()
		if err := s.repo.UpdateKnowledge(ctx, existingKnowledge); err != nil {
			logger.Errorf(ctx, "Failed to update existing knowledge: %v", err)
			return nil, err
		}
		return existingKnowledge, types.NewDuplicateURLError(existingKnowledge)
	}
	if err := s.checkCreateKnowledgeEntitlement(ctx, kbID, fileType, maxFileURLSize); err != nil {
		return nil, err
	}

	// Check storage quota
	tenantInfo := ctx.Value(types.TenantInfoContextKey).(*types.Tenant)
	storageQuota := effectiveStorageQuota(tenantInfo, time.Now().UTC())
	if storageQuota > 0 && tenantInfo.StorageUsed >= storageQuota {
		logger.Error(ctx, "Storage quota exceeded")
		return nil, types.NewStorageQuotaExceededError()
	}

	// Create knowledge record
	knowledge := &types.Knowledge{
		ID:               uuid.New().String(),
		TenantID:         tenantID,
		KnowledgeBaseID:  kbID,
		Type:             "file_url",
		Channel:          defaultChannel(channel),
		Title:            title,
		FileName:         displayName,
		FileType:         fileType,
		Source:           fileURL,
		FileHash:         fileHash,
		ParseStatus:      "pending",
		EnableStatus:     "disabled",
		CreatedAt:        time.Now(),
		UpdatedAt:        time.Now(),
		EmbeddingModelID: kb.EmbeddingModelID,
	}
	if knowledge.Title == "" {
		knowledge.Title = displayName
	}

	eff, err := resolveFileImportProcessConfig(ctx, kb, fileType, processOverrides, enableMultimodel)
	if err != nil {
		return nil, err
	}
	if processOverrides != nil {
		if err := knowledge.SetProcessOverrides(processOverrides); err != nil {
			logger.Errorf(ctx, "Failed to set process overrides: %v", err)
			return nil, err
		}
	}

	if err := s.repo.CreateKnowledge(ctx, knowledge); err != nil {
		logger.Errorf(ctx, "Failed to create knowledge record: %v", err)
		return nil, err
	}
	// Set tag relations
	if err := s.setAndAttachKnowledgeTags(ctx, tenantID, kbID, knowledge, tagIDs); err != nil {
		logger.Errorf(ctx, "Failed to set knowledge tags, knowledge ID: %s, error: %v", knowledge.ID, err)
		return nil, err
	}

	// Build async task payload
	enableMultimodelValue := eff.EnableMultimodel
	enableQuestionGeneration := eff.QuestionGenerationConfig.Enabled
	questionCount := eff.QuestionGenerationConfig.QuestionCount
	if questionCount <= 0 {
		questionCount = 3
	}

	lang := types.LanguageFromContextOrDefault(ctx)
	taskPayload := types.DocumentProcessPayload{
		TenantID:                 tenantID,
		KnowledgeID:              knowledge.ID,
		KnowledgeBaseID:          kbID,
		FileURL:                  fileURL,
		FileName:                 fileName,
		FileType:                 fileType,
		EnableMultimodel:         enableMultimodelValue,
		EnableQuestionGeneration: enableQuestionGeneration,
		QuestionCount:            questionCount,
		Language:                 lang,
	}

	langfuse.InjectTracing(ctx, &taskPayload)
	payloadBytes, err := json.Marshal(taskPayload)
	if err != nil {
		logger.Errorf(ctx, "Failed to marshal file URL process task payload: %v", err)
		s.markKnowledgeEnqueueFailed(ctx, knowledge)
		recordKBActivity(ctx, s.audit, tenantID, kbID, types.AuditActionKnowledgeCreated,
			"knowledge", knowledge.ID, types.AuditOutcomeFailed, map[string]any{
				"title": knowledge.Title, "source_type": "file_url", "file_type": knowledge.FileType,
				"processing_status": "failed", "failure_stage": "enqueue",
			})
		return knowledge, nil
	}

	task := asynq.NewTask(
		types.TypeDocumentProcess,
		payloadBytes,
		documentProcessTaskOptions(s.config)...,
	)
	info, err := s.task.Enqueue(task)
	if err != nil {
		logger.Errorf(ctx, "Failed to enqueue file URL process task: %v", err)
		s.markKnowledgeEnqueueFailed(ctx, knowledge)
		recordKBActivity(ctx, s.audit, tenantID, kbID, types.AuditActionKnowledgeCreated,
			"knowledge", knowledge.ID, types.AuditOutcomeFailed, map[string]any{
				"title": knowledge.Title, "source_type": "file_url", "file_type": knowledge.FileType,
				"processing_status": "failed", "failure_stage": "enqueue",
			})
		return knowledge, nil
	}
	recordKBActivity(ctx, s.audit, tenantID, kbID, types.AuditActionKnowledgeCreated,
		"knowledge", knowledge.ID, types.AuditOutcomeAccepted, map[string]any{
			"title": knowledge.Title, "source_type": "file_url", "file_type": knowledge.FileType,
			"processing_status": "pending", "task_id": info.ID, "trigger": kbActivityTrigger(ctx),
		})
	logger.Infof(ctx, "Enqueued file URL process task: id=%s queue=%s knowledge_id=%s", info.ID, info.Queue, knowledge.ID)

	enqueueDataTableSummaryIfNeeded(ctx, s.task, tenantID, knowledge.ID, fileName, fileType, kb.SummaryModelID, kb.EmbeddingModelID)

	logger.Infof(ctx, "Knowledge from file URL created successfully, ID: %s", knowledge.ID)
	return knowledge, nil
}

// CreateKnowledgeFromPassage creates a knowledge entry from text passages
func (s *knowledgeService) CreateKnowledgeFromPassage(ctx context.Context,
	kbID string, passage []string, channel string,
) (*types.Knowledge, error) {
	return s.createKnowledgeFromPassageInternal(ctx, kbID, passage, false, channel)
}

// CreateKnowledgeFromPassageSync creates a knowledge entry from text passages and waits for indexing to complete.
func (s *knowledgeService) CreateKnowledgeFromPassageSync(ctx context.Context,
	kbID string, passage []string, channel string,
) (*types.Knowledge, error) {
	return s.createKnowledgeFromPassageInternal(ctx, kbID, passage, true, channel)
}

// resolveManualCuratedFields keeps an existing editorial summary when the
// ordinary editor saves a curated document without knowing these API fields.
// Explicitly setting skip_auto_enrichment=false opts back into normal
// automatic post-processing.
func resolveManualCuratedFields(
	payload *types.ManualKnowledgePayload,
	previous *types.ManualKnowledgeMetadata,
) (string, bool, error) {
	skip := previous != nil && previous.SkipAutoEnrichment
	if payload.SkipAutoEnrichment != nil {
		skip = *payload.SkipAutoEnrichment
	}
	summary := strings.TrimSpace(payload.CuratedSummary)
	if summary == "" && skip && previous != nil && previous.SkipAutoEnrichment {
		summary = previous.CuratedSummary
	}
	if !skip && summary != "" {
		return "", false, werrors.NewValidationError("人工摘要需要启用跳过自动后处理")
	}
	if skip && summary == "" {
		return "", false, werrors.NewValidationError("跳过自动后处理时需要人工摘要")
	}
	if len([]rune(summary)) > 2000 {
		return "", false, werrors.NewValidationError("人工摘要最多2000个字符")
	}
	safeSummary, ok := secutils.ValidateInput(summary)
	if !ok {
		return "", false, werrors.NewValidationError("人工摘要包含非法字符")
	}
	return safeSummary, skip, nil
}

// CreateKnowledgeFromManual creates or saves manual Markdown knowledge content.
func (s *knowledgeService) CreateKnowledgeFromManual(ctx context.Context,
	kbID string, payload *types.ManualKnowledgePayload, channel string,
) (*types.Knowledge, error) {
	logger.Info(ctx, "Start creating manual knowledge entry")

	if payload == nil {
		return nil, werrors.NewBadRequestError("请求内容不能为空")
	}

	cleanContent := secutils.CleanMarkdown(payload.Content)
	if strings.TrimSpace(cleanContent) == "" {
		return nil, werrors.NewValidationError("内容不能为空")
	}
	if len([]rune(cleanContent)) > manualContentMaxLength {
		return nil, werrors.NewValidationError(fmt.Sprintf("内容长度超出限制（最多%d个字符）", manualContentMaxLength))
	}

	safeTitle, ok := secutils.ValidateInput(payload.Title)
	if !ok {
		return nil, werrors.NewValidationError("标题包含非法字符或超出长度限制")
	}

	status := strings.ToLower(strings.TrimSpace(payload.Status))
	if status == "" {
		status = types.ManualKnowledgeStatusDraft
	}
	if status != types.ManualKnowledgeStatusDraft && status != types.ManualKnowledgeStatusPublish {
		return nil, werrors.NewValidationError("状态仅支持 draft 或 publish")
	}
	curatedSummary, skipAutoEnrichment, err := resolveManualCuratedFields(payload, nil)
	if err != nil {
		return nil, err
	}

	kb, err := s.kbService.GetKnowledgeBaseByID(ctx, kbID)
	if err != nil {
		logger.Errorf(ctx, "Failed to get knowledge base: %v", err)
		return nil, err
	}

	if err := s.checkStorageEngineConfigured(ctx, kb); err != nil {
		return nil, err
	}
	if err := s.checkCreateKnowledgeEntitlement(ctx, kbID, types.KnowledgeTypeManual, int64(len(cleanContent))); err != nil {
		return nil, err
	}

	tenantID := ctx.Value(types.TenantIDContextKey).(uint64)
	now := time.Now()
	title := safeTitle
	if title == "" {
		title = fmt.Sprintf("Knowledge-%s", now.Format("20060102-150405"))
	}

	fileName := ensureManualFileName(title)
	meta := types.NewManualKnowledgeMetadata(cleanContent, status, 1)
	meta.CuratedSummary = curatedSummary
	meta.SkipAutoEnrichment = skipAutoEnrichment

	knowledge := &types.Knowledge{
		TenantID:         tenantID,
		KnowledgeBaseID:  kbID,
		Type:             types.KnowledgeTypeManual,
		Channel:          defaultChannel(channel),
		Title:            title,
		Description:      curatedSummary,
		Source:           types.KnowledgeTypeManual,
		ParseStatus:      types.ManualKnowledgeStatusDraft,
		EnableStatus:     "disabled",
		CreatedAt:        now,
		UpdatedAt:        now,
		EmbeddingModelID: kb.EmbeddingModelID,
		FileName:         fileName,
		FileType:         types.KnowledgeTypeManual,
	}
	if err := knowledge.SetManualMetadata(meta); err != nil {
		logger.Errorf(ctx, "Failed to set manual metadata: %v", err)
		return nil, err
	}
	knowledge.EnsureManualDefaults()

	if status == types.ManualKnowledgeStatusPublish {
		knowledge.ParseStatus = "pending"
	}

	if status == types.ManualKnowledgeStatusPublish {
		if _, err := ApplyKnowledgeProcessOverrides(ctx, kb, knowledge, payload.ProcessConfig, nil, nil); err != nil {
			return nil, err
		}
	}

	if err := s.repo.CreateKnowledge(ctx, knowledge); err != nil {
		logger.Errorf(ctx, "Failed to create manual knowledge record: %v", err)
		return nil, err
	}
	// Set tag relations
	if err := s.setAndAttachKnowledgeTags(ctx, tenantID, kbID, knowledge, payload.TagIDs); err != nil {
		logger.Errorf(ctx, "Failed to set knowledge tags, knowledge ID: %s, error: %v", knowledge.ID, err)
		return nil, err
	}

	// Claim the body's files immediately, before publishing. A draft saved from
	// a chat answer must already own them: the message it came from could be
	// deleted while the draft is still unpublished.
	s.bindContentResources(ctx, tenantID, knowledge.ID, cleanContent)

	if status == types.ManualKnowledgeStatusPublish {
		logger.Infof(ctx, "Manual knowledge created, enqueuing async processing task, ID: %s", knowledge.ID)
		taskID, err := s.enqueueManualProcessing(ctx, knowledge, cleanContent, false)
		if err != nil {
			logger.Errorf(ctx, "Failed to enqueue manual processing task for new knowledge: %v", err)
			// Non-fatal: mark as failed so user can retry
			knowledge.ParseStatus = "failed"
			knowledge.ErrorMessage = "Failed to enqueue processing task"
			s.repo.UpdateKnowledge(ctx, knowledge)
			recordKBActivity(ctx, s.audit, tenantID, kbID, types.AuditActionKnowledgeCreated,
				"knowledge", knowledge.ID, types.AuditOutcomeFailed, map[string]any{
					"title": knowledge.Title, "source_type": "manual", "status": status,
					"processing_status": "failed", "failure_stage": "enqueue",
				})
		} else {
			recordKBActivity(ctx, s.audit, tenantID, kbID, types.AuditActionKnowledgeCreated,
				"knowledge", knowledge.ID, types.AuditOutcomeAccepted, map[string]any{
					"title": knowledge.Title, "source_type": "manual", "status": status,
					"processing_status": "pending", "task_id": taskID, "trigger": kbActivityTrigger(ctx),
				})
		}
	} else {
		recordKBActivity(ctx, s.audit, tenantID, kbID, types.AuditActionKnowledgeCreated,
			"knowledge", knowledge.ID, types.AuditOutcomeSuccess, map[string]any{
				"title": knowledge.Title, "source_type": "manual", "status": status,
			})
	}

	return knowledge, nil
}

// createKnowledgeFromPassageInternal consolidates the common logic for creating knowledge from passages.
// When syncMode is true, chunk processing is performed synchronously; otherwise, it's processed asynchronously.
func (s *knowledgeService) createKnowledgeFromPassageInternal(ctx context.Context,
	kbID string, passage []string, syncMode bool, channel string,
) (*types.Knowledge, error) {
	if syncMode {
		logger.Info(ctx, "Start creating knowledge from passage (sync)")
	} else {
		logger.Info(ctx, "Start creating knowledge from passage")
	}
	logger.Infof(ctx, "Knowledge base ID: %s, passage count: %d", kbID, len(passage))

	// 验证段落内容安全性
	safePassages := make([]string, 0, len(passage))
	for i, p := range passage {
		safePassage, isValid := secutils.ValidateInput(p)
		if !isValid {
			logger.Errorf(ctx, "Invalid passage content at index %d", i)
			return nil, werrors.NewValidationError(fmt.Sprintf("段落 %d 包含非法内容", i+1))
		}
		safePassages = append(safePassages, safePassage)
	}

	// Get knowledge base configuration
	logger.Info(ctx, "Getting knowledge base configuration")
	kb, err := s.kbService.GetKnowledgeBaseByID(ctx, kbID)
	if err != nil {
		logger.Errorf(ctx, "Failed to get knowledge base: %v", err)
		return nil, err
	}
	totalBytes := int64(0)
	for _, item := range safePassages {
		totalBytes += int64(len(item))
	}
	if err := s.checkCreateKnowledgeEntitlement(ctx, kbID, "passage", totalBytes); err != nil {
		return nil, err
	}

	// Create knowledge record
	if syncMode {
		logger.Info(ctx, "Creating knowledge record (sync)")
	} else {
		logger.Info(ctx, "Creating knowledge record")
	}
	knowledge := &types.Knowledge{
		ID:               uuid.New().String(),
		TenantID:         ctx.Value(types.TenantIDContextKey).(uint64),
		KnowledgeBaseID:  kbID,
		Type:             "passage",
		Channel:          defaultChannel(channel),
		ParseStatus:      "pending",
		EnableStatus:     "disabled",
		CreatedAt:        time.Now(),
		UpdatedAt:        time.Now(),
		EmbeddingModelID: kb.EmbeddingModelID,
	}

	// Save knowledge record
	logger.Infof(ctx, "Saving knowledge record to database, ID: %s", knowledge.ID)
	if err := s.repo.CreateKnowledge(ctx, knowledge); err != nil {
		logger.Errorf(ctx, "Failed to create knowledge record: %v", err)
		return nil, err
	}
	// Process passages
	if syncMode {
		logger.Info(ctx, "Processing passage synchronously")
		s.processDocumentFromPassage(ctx, kb, knowledge, safePassages)
		recordKBActivity(ctx, s.audit, knowledge.TenantID, kbID, types.AuditActionKnowledgeCreated,
			"knowledge", knowledge.ID, types.AuditOutcomeSuccess, map[string]any{
				"title": knowledge.Title, "source_type": "passage", "processing_status": knowledge.ParseStatus,
			})
		logger.Infof(ctx, "Knowledge from passage created successfully (sync), ID: %s", knowledge.ID)
	} else {
		// Enqueue passage processing task to Asynq
		logger.Info(ctx, "Enqueuing passage processing task to Asynq")
		tenantID := ctx.Value(types.TenantIDContextKey).(uint64)

		// Check question generation config
		enableQuestionGeneration := false
		questionCount := 3 // default
		if kb.QuestionGenerationConfig != nil && kb.QuestionGenerationConfig.Enabled {
			enableQuestionGeneration = true
			if kb.QuestionGenerationConfig.QuestionCount > 0 {
				questionCount = kb.QuestionGenerationConfig.QuestionCount
			}
		}

		lang := types.LanguageFromContextOrDefault(ctx)
		taskPayload := types.DocumentProcessPayload{
			TenantID:                 tenantID,
			KnowledgeID:              knowledge.ID,
			KnowledgeBaseID:          kbID,
			Passages:                 safePassages,
			EnableMultimodel:         false, // 文本段落不支持多模态
			EnableQuestionGeneration: enableQuestionGeneration,
			QuestionCount:            questionCount,
			Language:                 lang,
		}

		langfuse.InjectTracing(ctx, &taskPayload)
		payloadBytes, err := json.Marshal(taskPayload)
		if err != nil {
			logger.Errorf(ctx, "Failed to marshal passage process task payload: %v", err)
			s.markKnowledgeEnqueueFailed(ctx, knowledge)
			recordKBActivity(ctx, s.audit, knowledge.TenantID, kbID, types.AuditActionKnowledgeCreated,
				"knowledge", knowledge.ID, types.AuditOutcomeFailed, map[string]any{
					"title": knowledge.Title, "source_type": "passage",
					"processing_status": "failed", "failure_stage": "enqueue",
				})
			// 即使入队失败，也返回knowledge
			return knowledge, nil
		}

		task := asynq.NewTask(
			types.TypeDocumentProcess,
			payloadBytes,
			documentProcessTaskOptions(s.config, asynq.MaxRetry(3))...,
		)
		info, err := s.task.Enqueue(task)
		if err != nil {
			logger.Errorf(ctx, "Failed to enqueue passage process task: %v", err)
			s.markKnowledgeEnqueueFailed(ctx, knowledge)
			recordKBActivity(ctx, s.audit, knowledge.TenantID, kbID, types.AuditActionKnowledgeCreated,
				"knowledge", knowledge.ID, types.AuditOutcomeFailed, map[string]any{
					"title": knowledge.Title, "source_type": "passage",
					"processing_status": "failed", "failure_stage": "enqueue",
				})
			return knowledge, nil
		}
		recordKBActivity(ctx, s.audit, knowledge.TenantID, kbID, types.AuditActionKnowledgeCreated,
			"knowledge", knowledge.ID, types.AuditOutcomeAccepted, map[string]any{
				"title": knowledge.Title, "source_type": "passage", "processing_status": "pending",
				"task_id": info.ID, "trigger": kbActivityTrigger(ctx),
			})
		logger.Infof(ctx, "Enqueued passage process task: id=%s queue=%s knowledge_id=%s", info.ID, info.Queue, knowledge.ID)
		logger.Infof(ctx, "Knowledge from passage created successfully, ID: %s", knowledge.ID)
	}
	return knowledge, nil
}

// UpdateManualKnowledge updates manual Markdown knowledge content.
// For publish status, the heavy operations (cleanup old indexes, re-chunking,
// re-embedding) are offloaded to an Asynq task so the HTTP response returns quickly.
func (s *knowledgeService) UpdateManualKnowledge(ctx context.Context,
	knowledgeID string, payload *types.ManualKnowledgePayload,
) (*types.Knowledge, error) {
	logger.Info(ctx, "Start updating manual knowledge entry")
	if payload == nil {
		return nil, werrors.NewBadRequestError("请求内容不能为空")
	}

	cleanContent := secutils.CleanMarkdown(payload.Content)
	if strings.TrimSpace(cleanContent) == "" {
		return nil, werrors.NewValidationError("内容不能为空")
	}
	if len([]rune(cleanContent)) > manualContentMaxLength {
		return nil, werrors.NewValidationError(fmt.Sprintf("内容长度超出限制（最多%d个字符）", manualContentMaxLength))
	}

	safeTitle, ok := secutils.ValidateInput(payload.Title)
	if !ok {
		return nil, werrors.NewValidationError("标题包含非法字符或超出长度限制")
	}

	status := strings.ToLower(strings.TrimSpace(payload.Status))
	if status == "" {
		status = types.ManualKnowledgeStatusDraft
	}
	if status != types.ManualKnowledgeStatusDraft && status != types.ManualKnowledgeStatusPublish {
		return nil, werrors.NewValidationError("状态仅支持 draft 或 publish")
	}
	tenantID := ctx.Value(types.TenantIDContextKey).(uint64)
	existing, err := s.repo.GetKnowledgeByID(ctx, tenantID, knowledgeID)
	if err != nil {
		logger.Errorf(ctx, "Failed to load knowledge: %v", err)
		return nil, err
	}
	if !existing.IsManual() {
		return nil, werrors.NewBadRequestError("仅支持手工知识的在线编辑")
	}
	previousMeta, err := existing.ManualMetadata()
	if err != nil {
		return nil, err
	}
	previousOverrides, err := existing.ProcessOverrides()
	if err != nil {
		return nil, err
	}
	curatedSummary, skipAutoEnrichment, err := resolveManualCuratedFields(payload, previousMeta)
	if err != nil {
		return nil, err
	}

	kb, err := s.kbService.GetKnowledgeBaseByID(ctx, existing.KnowledgeBaseID)
	if err != nil {
		logger.Errorf(ctx, "Failed to get knowledge base for manual update: %v", err)
		return nil, err
	}

	var version int
	if meta, err := existing.ManualMetadata(); err == nil && meta != nil {
		version = meta.Version + 1
	} else {
		version = 1
	}

	meta := types.NewManualKnowledgeMetadata(cleanContent, status, version)
	meta.CuratedSummary = curatedSummary
	meta.SkipAutoEnrichment = skipAutoEnrichment
	if err := existing.SetManualMetadata(meta); err != nil {
		logger.Errorf(ctx, "Failed to set manual metadata during update: %v", err)
		return nil, err
	}
	// SetManualMetadata replaces the metadata JSON. Preserve the old process
	// overrides when an ordinary editor does not submit a new config.
	if payload.ProcessConfig == nil && previousOverrides != nil {
		if err := existing.SetProcessOverrides(previousOverrides); err != nil {
			return nil, err
		}
	}

	if safeTitle != "" {
		existing.Title = safeTitle
	} else if existing.Title == "" {
		existing.Title = fmt.Sprintf("手工知识-%s", time.Now().Format("20060102-150405"))
	}
	existing.FileName = ensureManualFileName(existing.Title)
	existing.FileType = types.KnowledgeTypeManual
	existing.Type = types.KnowledgeTypeManual
	existing.Source = types.KnowledgeTypeManual
	existing.EnableStatus = "disabled"
	existing.UpdatedAt = time.Now()
	existing.EmbeddingModelID = kb.EmbeddingModelID

	if status == types.ManualKnowledgeStatusDraft {
		existing.ParseStatus = types.ManualKnowledgeStatusDraft
		existing.Description = curatedSummary
		existing.ProcessedAt = nil

		if err := s.repo.UpdateKnowledge(ctx, existing); err != nil {
			logger.Errorf(ctx, "Failed to persist manual draft: %v", err)
			return nil, err
		}
		s.bindContentResources(ctx, tenantID, existing.ID, cleanContent)
		recordKBActivity(ctx, s.audit, tenantID, existing.KnowledgeBaseID, types.AuditActionKnowledgeUpdated,
			"knowledge", existing.ID, types.AuditOutcomeSuccess, map[string]any{
				"title": existing.Title, "status": status,
			})
		return existing, nil
	}

	// Publish: persist pending status and enqueue async task for cleanup + re-indexing
	existing.ParseStatus = "pending"
	existing.Description = curatedSummary
	existing.ProcessedAt = nil

	if _, err := ApplyKnowledgeProcessOverrides(ctx, kb, existing, payload.ProcessConfig, nil, nil); err != nil {
		return nil, err
	}

	if err := s.repo.UpdateKnowledge(ctx, existing); err != nil {
		logger.Errorf(ctx, "Failed to persist manual knowledge before indexing: %v", err)
		return nil, err
	}
	if skipAutoEnrichment && kb.IsWikiEnabled() {
		s.prepareWikiForReparse(ctx, existing)
	}

	logger.Infof(ctx, "Manual knowledge updated, enqueuing async processing task, ID: %s", existing.ID)
	taskID, err := s.enqueueManualProcessing(ctx, existing, cleanContent, true)
	if err != nil {
		logger.Errorf(ctx, "Failed to enqueue manual processing task: %v", err)
		// Non-fatal: mark as failed so user can retry
		existing.ParseStatus = "failed"
		existing.ErrorMessage = "Failed to enqueue processing task"
		s.repo.UpdateKnowledge(ctx, existing)
		recordKBActivity(ctx, s.audit, tenantID, existing.KnowledgeBaseID, types.AuditActionKnowledgeUpdated,
			"knowledge", existing.ID, types.AuditOutcomeFailed, map[string]any{
				"title": existing.Title, "status": status,
				"processing_status": "failed", "failure_stage": "enqueue",
			})
		return nil, werrors.NewInternalServerError("Failed to submit processing task")
	}
	recordKBActivity(ctx, s.audit, tenantID, existing.KnowledgeBaseID, types.AuditActionKnowledgeUpdated,
		"knowledge", existing.ID, types.AuditOutcomeAccepted, map[string]any{
			"title": existing.Title, "status": status, "processing_status": "pending",
			"task_id": taskID, "trigger": kbActivityTrigger(ctx),
		})
	return existing, nil
}

// enqueueManualProcessing enqueues a manual:process Asynq task for async cleanup + re-indexing.
func (s *knowledgeService) enqueueManualProcessing(ctx context.Context,
	knowledge *types.Knowledge, content string, needCleanup bool,
) (string, error) {
	requestID, _ := types.RequestIDFromContext(ctx)
	payload := types.ManualProcessPayload{
		RequestId:       requestID,
		TenantID:        knowledge.TenantID,
		KnowledgeID:     knowledge.ID,
		KnowledgeBaseID: knowledge.KnowledgeBaseID,
		Content:         content,
		NeedCleanup:     needCleanup,
	}
	langfuse.InjectTracing(ctx, &payload)
	payloadBytes, err := json.Marshal(payload)
	if err != nil {
		return "", fmt.Errorf("failed to marshal manual process payload: %w", err)
	}

	task := asynq.NewTask(types.TypeManualProcess, payloadBytes,
		asynq.Queue(types.QueueDefault), asynq.MaxRetry(3), asynq.Timeout(30*time.Minute))
	info, err := s.task.Enqueue(task)
	if err != nil {
		return "", fmt.Errorf("failed to enqueue manual process task: %w", err)
	}
	logger.Infof(ctx, "Enqueued manual process task: knowledge_id=%s, asynq_id=%s", knowledge.ID, info.ID)
	return info.ID, nil
}

// markKnowledgeEnqueueFailed prevents a durable knowledge row from remaining
// indefinitely "pending" when its background processing task was never
// created. The API may still return the row so callers can retry it.
func (s *knowledgeService) markKnowledgeEnqueueFailed(ctx context.Context, knowledge *types.Knowledge) {
	if knowledge == nil {
		return
	}
	knowledge.ParseStatus = "failed"
	knowledge.ErrorMessage = "Failed to enqueue processing task"
	if err := s.repo.UpdateKnowledge(ctx, knowledge); err != nil {
		logger.Errorf(ctx, "Failed to mark knowledge as failed after enqueue error: %v", err)
	}
}

func ensureManualFileName(title string) string {
	if title == "" {
		return fmt.Sprintf("manual-%s%s", time.Now().Format("20060102-150405"), manualFileExtension)
	}
	trimmed := strings.TrimSpace(title)
	if strings.HasSuffix(strings.ToLower(trimmed), manualFileExtension) {
		return trimmed
	}
	return trimmed + manualFileExtension
}

// sanitizeManualDownloadFilename converts a knowledge title into a safe .md
// download filename. Characters that are illegal or dangerous in HTTP header
// values and file-system paths are removed or replaced; a blank result falls
// back to "untitled".
func sanitizeManualDownloadFilename(title string) string {
	safeName := strings.NewReplacer(
		"\n", "", "\r", "", "\t", "", "/", "-", "\\", "-", "\"", "'",
	).Replace(title)
	if strings.TrimSpace(safeName) == "" {
		safeName = "untitled"
	}
	if !strings.HasSuffix(strings.ToLower(safeName), manualFileExtension) {
		safeName += manualFileExtension
	}
	return safeName
}

// bindContentResources claims every stored file the body references on behalf
// of a knowledge entry.
//
// A manual document routinely points at files it did not upload: an answer saved
// from a chat carries the very `resource://` handles the assistant message still
// shows. Claiming them is what makes that copy safe — no bytes are duplicated,
// and neither the message nor the document can delete a file the other still
// needs. Handles belonging to another workspace are skipped, so a pasted
// reference cannot pull in a file the caller may not read.
//
// Best-effort by design: the document is already saved, and a missed claim
// degrades to the old behaviour rather than failing the save.
func (s *knowledgeService) bindContentResources(
	ctx context.Context, tenantID uint64, knowledgeID, content string,
) {
	if s.resourceCatalog == nil || knowledgeID == "" {
		return
	}
	for _, ref := range types.ScanResourceReferences(content) {
		resource, err := s.resourceCatalog.Resolve(ctx, ref)
		if err != nil || resource == nil {
			logger.Warnf(ctx, "Skip binding unknown resource %s to knowledge %s: %v", ref, knowledgeID, err)
			continue
		}
		if resource.TenantID != tenantID {
			logger.Warnf(ctx, "Skip binding cross-workspace resource %s to knowledge %s", ref, knowledgeID)
			continue
		}
		if err := s.resourceCatalog.Bind(
			ctx, ref, types.ResourceOwnerKnowledge, knowledgeID, types.ResourceRelationAttachment,
		); err != nil {
			logger.Warnf(ctx, "Failed to bind resource %s to knowledge %s: %v", ref, knowledgeID, err)
		}
	}
}

func (s *knowledgeService) triggerManualProcessing(ctx context.Context,
	kb *types.KnowledgeBase, knowledge *types.Knowledge, content string, doSync bool,
) {
	clean := strings.TrimSpace(content)
	if clean == "" {
		return
	}

	// Resolve embedded data:base64 images and remote http(s) images → storage, replace URLs.
	// Runs before chunking so chunks contain stable provider:// URLs.
	var resolvedImages []docparser.StoredImage
	if s.imageResolver != nil {
		fileSvc := s.resolveFileService(ctx, kb)
		afterDataURI, fromDataURI, _ := s.imageResolver.ResolveDataURIImages(ctx, clean, fileSvc, knowledge.TenantID)
		if len(fromDataURI) > 0 {
			logger.Infof(ctx, "Resolved %d data-URI images for manual knowledge %s", len(fromDataURI), knowledge.ID)
			clean = afterDataURI
			resolvedImages = append(resolvedImages, fromDataURI...)
		}
		updatedContent, storedImages, resolveErr := s.imageResolver.ResolveRemoteImages(ctx, clean, fileSvc, knowledge.TenantID)
		if resolveErr != nil {
			logger.Warnf(ctx, "Remote image resolution partially failed: %v", resolveErr)
		}
		if len(storedImages) > 0 {
			logger.Infof(ctx, "Resolved %d remote images for manual knowledge %s", len(storedImages), knowledge.ID)
			clean = updatedContent
			resolvedImages = append(resolvedImages, storedImages...)
		}
	}

	// Re-claim the body's stored files. This runs after cleanupKnowledgeResources
	// released the previous run's claims, so a republished document keeps the
	// files its new body still references.
	s.bindContentResources(ctx, knowledge.TenantID, knowledge.ID, clean)

	// Keep manually entered CRLF text aligned with the LF values sent by the
	// chunking preview endpoint.
	clean = chunker.NormalizeLineEndings(clean)

	processOverrides, _ := knowledge.ProcessOverrides()
	eff := ResolveProcessConfig(kb, processOverrides)
	manualMeta, metaErr := knowledge.ManualMetadata()
	if metaErr != nil {
		logger.Warnf(ctx, "Failed to read manual metadata for %s: %v", knowledge.ID, metaErr)
	}
	curatedManual := metaErr == nil && manualMeta != nil && manualMeta.SkipAutoEnrichment

	// Manual content is markdown - chunk directly with Go chunker
	chunkCfg := buildSplitterConfigFromChunking(eff.ChunkingConfig)

	var parsed []types.ParsedChunk
	opts := ProcessChunksOptions{
		EnableMultimodel: eff.EnableMultimodel && len(resolvedImages) > 0 && !curatedManual,
		StoredImages:     resolvedImages,
	}
	if eff.QuestionGenerationConfig.Enabled && !curatedManual {
		opts.EnableQuestionGeneration = true
		opts.QuestionCount = eff.QuestionGenerationConfig.QuestionCount
		if opts.QuestionCount <= 0 {
			opts.QuestionCount = 3
		}
	}

	if eff.ChunkingConfig.EnableParentChild {
		parentCfg, childCfg := buildParentChildConfigs(eff.ChunkingConfig, chunkCfg)
		pcResult := chunker.SplitParentChild(clean, parentCfg, childCfg)
		parsed = make([]types.ParsedChunk, len(pcResult.Children))
		for i, c := range pcResult.Children {
			parsed[i] = types.ParsedChunk{
				Content:       c.Content,
				ContextHeader: c.ContextHeader,
				Seq:           c.Seq,
				Start:         c.Start,
				End:           c.End,
				ParentIndex:   c.ParentIndex,
			}
		}
		parentChunks := make([]types.ParsedParentChunk, len(pcResult.Parents))
		for i, p := range pcResult.Parents {
			parentChunks[i] = types.ParsedParentChunk{Content: p.Content, Seq: p.Seq, Start: p.Start, End: p.End}
		}
		opts.ParentChunks = parentChunks
	} else {
		splitChunks := chunker.Split(clean, chunkCfg)
		parsed = make([]types.ParsedChunk, len(splitChunks))
		for i, c := range splitChunks {
			parsed[i] = types.ParsedChunk{
				Content:       c.Content,
				ContextHeader: c.ContextHeader,
				Seq:           c.Seq,
				Start:         c.Start,
				End:           c.End,
			}
		}
	}

	if doSync {
		s.processChunks(ctx, kb, knowledge, parsed, opts)
		return
	}

	newCtx := logger.CloneContext(ctx)
	go s.processChunks(newCtx, kb, knowledge, parsed, opts)
}
